### PR TITLE
Combine the projects Richard left behind (and refactors)

### PR DESCRIPTION
**Pull request by stevefan1999-personal**
This PR will do the following:

1. Pull in https://github.com/Myina/peer-talk and its git histories
2. Pull in https://github.com/ipfs-shipyard/net-ipfs-http-client and its git histories
3. Pull in https://github.com/stevefan1999-personal/net-ipfs-engine and its git histories
4. Rewrite all the dependencies to use internal project references
5. Do a medium-large scale refactor (we still have unit testes so no worries)

It is done in a way so that all the former git contributions by @richardschneider will be pass on. Apparently, he has passed away, so it is safe to say this code ownership reassumption would be fine to him.

TODO:
1. Fix CI, notably unit testing
2. Fix documentation generation
3. Fix Nuget publishing (we can publish to both public nuget for release and Github Packages for cutting edge)
4. Make sure all dependencies are up-to-date

### CODE REVIEW

**Comment by stevefan1999-personal** [comment]
Seems like the work is good in progress, a preliminary MSBuild Test shows about 80% of the tests are passing. There is an integration test that requires opening a daemon so that contributed a lot of test case failures, and if we isolated that we got around 95% pass rate.

**Comment by erikma** [comment]
Consider implementing #20 as part of this to reduce package version redundancies. Part of that work item involves upgrading to latest package versions, which you also list here. (Alternately if you want to get this PR complete ASAP #20 can follow.)

**Comment by stevefan1999-personal** [comment]
@Arlodotexe @Derrick- sorry to bother but both of you are the last two people who worked on it before. I think this PR is ready, I wonder if you guy would like to review it, thanks.

**Review by erikmav — APPROVED** [review]

**Comment by Derrick-** [comment]
This looks good to me. I'm not sure what's going on with @Arlodotexe. My PR is still pending too.
I'm really happy to see the work on this project. Perhaps a conversation about more repo maintainers would be beneficial.

**Review by Derrick- — APPROVED** [review]

**Comment by Arlodotexe** [comment]
> I'm really happy to see the work on this project. Perhaps a conversation about more repo maintainers would be beneficial.

I'm open to this, if we can find the right person. Contact me [on Discord](https://uwpcommunity.com/), we have an `#ipfs-shipyard` channel in the UWP/Windows App Community we use for communication on the .NET libraries.

**Comment by Arlodotexe** [comment]
@stevefan1999-personal In case you missed it, we've already pulled in, fixed up and shipped the [net-ipfs-http-client](https://github.com/ipfs-shipyard/net-ipfs-http-client).

Due to a combination of complexity, lack of developer resources, and ever-changing standards, we opted not to bring in Richard's peertalk or net-ipfs-engine implementation.

To bring these back, we'd need to
- Make sure the basic features still work
- Get it up to par with newer version of libp2p (not an easy task)
- Find someone willing and capable of spearheading the efforts
- Optionally, join and align with the Content Routing working group, alongside Kubo, Iroh and others.

Instead, we've scoped these projects working with the IPFS HTTP API and the Kubo RPC API.

If you need Kubo standalone in your application, the best option right now may be to use the official binary via [`KuboBootstrapper`](https://github.com/Arlodotexe/OwlCore.Kubo/blob/main/docs/KuboBootstrapper.md) in [OwlCore.Kubo](https://github.com/Arlodotexe/OwlCore.Kubo), at least until a more portable (and well-maintained) implementation is available, such as a WASM version.

You can read about our transition from Richard Schneider's libraries [here](https://github.com/richardschneider/net-ipfs-http-client/issues/728).

**Pull request closed without merging**
